
class MessageTypes:
    Get_Seed_Nodes = "Get_Seed_Nodes"
    Get_Neighbors = "Get_Neighbors"
    Get_Blockchain = "Get_Blockchain"
    Send_Transaction = "Send_Transaction"
    Send_Block = "Send_Block"
    Get_Seed_Nodes_Response = "Get_Seed_Nodes_Response"
    Get_Neighbors_Response = "Get_Neighbors_Response"
    Join_As_Miner = "Join_As_Miner"
    Join_As_Miner_Response = "Join_As_Miner_Response"
    Start_New_Block = "Start_New_Block"
    Start_New_Block_Response = "Start_New_Block_Response"
    Get_Blockchain_Response = "Get_Blockchain_Response"
    Send_Transaction_Response = "Send_Transaction_Response"
    Get_Block = "Get_Block"